# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Conifr' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
	
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'ArcKit', '~> 5.0.0.pre'
pod 'ArcKit/LocalStore', '~> 5.0.0.pre'
pod 'SwiftNotes'
pod 'PaginatedScrollView'
pod 'Motion'
pod 'Material'
pod 'Floaty'
pod 'SwiftLocation', '~> 3.1'
# Pods for Conifr

end
